### ISSUE TITLE
Go through the course feedback

### ISSUE THREAD

**Issue by fasterius** [NBISweden/workshop-reproducible-research#167]
Go through the course feedback and think about changing the schedule and time allotted for each tutorial, based on feedback.

**Comment by johnne** [comment]
I went back and had a look at previous course evaluations. Snakemake got similarly a majority in the Tricky but good or Too difficult category from April 2021, but looking at November 2020 it had a majority in the "Just right" with 1 response in "Easy but good". I don't think we've made the tutorial more difficult since then so maybe it has to do with the selection of applicants. Nevertheless we should think about if we can make the tutorial easier slightly.
